upstream-config:
  upstreams:
    - id: eth-upstream
      chain: polygon
      connectors:
        - type: json-rpc
          url: https://test.com
        - type: json-rpc
          url: https://test.com