name: Run tests

on:
  workflow_dispatch: null
  pull_request: null
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-go@v5
        with:
          go-version: '^1.24.0'

      - run: make generate-networks

      - name: Test
        run: make test
